from __future__ import annotations

import argparse
import pathlib
import re
import subprocess

from common import ROOT, compose_with_release, latest_backup, load_json, print_check, read_env


def validate_manifest(path: pathlib.Path, *, strict: bool) -> tuple[dict, list[tuple[str, str, str]]]:
    checks: list[tuple[str, str, str]] = []
    manifest = load_json(path)
    release = manifest.get("release", {})
    images = manifest.get("images", {})
    signature = manifest.get("signature", {})
    current_edition = read_env().get("IGNITION_EDITION", "community")

    checks.append(("PASS" if manifest.get("schemaVersion") == 1 else "FAIL", "schema", "schemaVersion=1"))
    checks.append(("PASS" if manifest.get("edition") == current_edition else ("FAIL" if strict else "WARN"), "edition", f"manifest={manifest.get('edition')} current={current_edition}"))
    checks.append(("PASS" if release.get("version") else "FAIL", "release", str(release.get("version", "missing"))))

    invalid = []
    for name, image in images.items():
        digest = image.get("digest", "")
        if not re.fullmatch(r"sha256:[a-fA-F0-9]{64}", digest):
            invalid.append(name)
    checks.append(("PASS" if not invalid else ("FAIL" if strict else "WARN"), "image digests", "all sha256 pinned" if not invalid else ", ".join(invalid)))

    signature_value = str(signature.get("value", ""))
    has_signature = (
        signature.get("algorithm") == "ed25519"
        and bool(signature_value)
        and "replace-with" not in signature_value
        and "base64-signature" not in signature_value
        and "placeholder" not in signature_value.lower()
    )
    checks.append(("PASS" if has_signature else ("FAIL" if strict else "WARN"), "signature", "ed25519 signature present" if has_signature else "missing or placeholder signature"))

    requires_backup = bool(manifest.get("migrations", {}).get("requiresBackup"))
    backup = latest_backup()
    checks.append(("PASS" if not requires_backup or backup else ("FAIL" if strict else "WARN"), "backup", backup.name if backup else "required backup missing"))
    checks.append(validate_extensions(release))
    return manifest, checks


def parse_version(value: str) -> tuple[int, ...]:
    return tuple(int(part) for part in re.findall(r"\d+", value))


def compare_versions(left: str, right: str) -> int:
    left_parts = parse_version(left)
    right_parts = parse_version(right)
    length = max(len(left_parts), len(right_parts))
    left_parts = left_parts + (0,) * (length - len(left_parts))
    right_parts = right_parts + (0,) * (length - len(right_parts))
    return (left_parts > right_parts) - (left_parts < right_parts)


def validate_extensions(release: dict) -> tuple[str, str, str]:
    core_version = str(release.get("coreVersion") or release.get("version") or "")
    extension_api = str(release.get("extensionApiVersion") or "")
    invalid: list[str] = []
    checked = 0
    for root_name in ["plugins", "themes", "custom-connectors"]:
        root = ROOT / root_name
        for manifest_path in root.rglob("ignition-extension.json"):
            checked += 1
            try:
                extension = load_json(manifest_path)
            except Exception:
                invalid.append(f"{manifest_path.relative_to(ROOT)}: invalid json")
                continue
            compatibility = extension.get("compatibility", {})
            if not isinstance(compatibility, dict):
                invalid.append(f"{manifest_path.relative_to(ROOT)}: missing compatibility")
                continue
            required_api = compatibility.get("extensionApi")
            min_core = compatibility.get("minCore")
            max_core = compatibility.get("maxCore")
            if required_api and str(required_api) != extension_api:
                invalid.append(f"{manifest_path.relative_to(ROOT)}: extensionApi {required_api} != {extension_api}")
            if min_core and compare_versions(core_version, str(min_core)) < 0:
                invalid.append(f"{manifest_path.relative_to(ROOT)}: minCore {min_core} > {core_version}")
            if max_core and compare_versions(core_version, str(max_core)) > 0:
                invalid.append(f"{manifest_path.relative_to(ROOT)}: maxCore {max_core} < {core_version}")
    if invalid:
        return ("FAIL", "extensions", "; ".join(invalid))
    return ("PASS", "extensions", f"{checked} manifest(s) compatible")


def write_release_override(manifest: dict) -> pathlib.Path:
    path = ROOT / ".self-hosted" / "docker-compose.release.yml"
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by scripts/update.py --apply.", "services:"]
    for service, image in manifest["images"].items():
        lines.append(f"  {service}:")
        lines.append(f"    image: {image['repository']}@{image['digest']}")
    path.write_text("\n".join(lines) + "\n")
    return path


parser = argparse.ArgumentParser()
parser.add_argument("--manifest", required=True)
parser.add_argument("--dry-run", action="store_true")
parser.add_argument("--apply", action="store_true")
args = parser.parse_args()

if args.dry_run == args.apply:
    raise SystemExit("Use exactly one of --dry-run or --apply")

manifest_path = pathlib.Path(args.manifest)
if not manifest_path.is_absolute():
    manifest_path = ROOT / manifest_path

manifest, checks = validate_manifest(manifest_path, strict=args.apply)
for check in checks:
    print_check(*check)

if args.dry_run:
    print("\nSELF_HOSTED_UPDATE_DRY_RUN_OK")
    raise SystemExit(0 if all(status != "FAIL" for status, _, _ in checks) else 1)

if any(status != "PASS" for status, _, _ in checks):
    raise SystemExit("\nSELF_HOSTED_UPDATE_APPLY_BLOCKED")

override = write_release_override(manifest)
services = list(manifest["images"].keys())
backup = latest_backup()
print_check("PASS", "release override", str(override))

try:
    compose_with_release(["pull", *services])
    compose_with_release(["up", "-d", "--no-build", *services, "nginx"])
    compose_with_release(["run", "--rm", "api", "bun", "run", "src/db/migrate.ts"])
    subprocess.run(["python3", "scripts/smoke.py"], cwd=ROOT, check=True)
except subprocess.CalledProcessError:
    if backup:
        print(f"\nSELF_HOSTED_UPDATE_FAILED_RESTORE_COMMAND python3 scripts/restore.py --backup {backup.name} --confirm {backup.name}")
    raise

print(f"\nSELF_HOSTED_UPDATE_APPLY_OK {manifest['release']['version']}")
